# wrangler.toml
name = 'bridge-os-worker'
main = "index.js"
compatibility_date = "2024-03-07"

# DedupeObject を完全に削除するための命令
[[migrations]]
tag = "v2"
deleted_classes = ["DedupeObject"]
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[vars]
GAS_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbykg3DTLB9hUO9NaHj9U38be_RAkOQRj7j75EU6vk3pNawX-c7kj-qSNIaIJgZqih12/exec"
